<?php

namespace AgileCreativeMinds\DevLoginLink\Http\Controllers;

use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Routing\Controller;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/**
 * Handles the dev login link authentication.
 *
 * This invokable controller processes signed URLs generated by the
 * dev:login-link command. It authenticates the specified user and
 * redirects them to the dashboard or home page.
 *
 * The route using this controller is protected by the 'signed'
 * middleware, ensuring URLs cannot be tampered with or reused
 * after expiration.
 */
class DevLoginController extends Controller
{
    /**
     * Handle the incoming request.
     */
    public function __invoke(Request $request, int $user): RedirectResponse
    {
        $userModel = config('auth.providers.users.model', 'App\\Models\\User');
        $userInstance = $userModel::findOrFail($user);

        Auth::login($userInstance, remember: false);

        // Redirect to dashboard if it exists, otherwise home
        if (Route::has('dashboard')) {
            return redirect()->route('dashboard');
        }

        return redirect('/');
    }
}
